In [1]:
import numpy as np

In [6]:
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[8,9,10],[11,12,13]])

In [7]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
B

array([[ 8,  9, 10],
       [11, 12, 13]])

In [14]:
vstck=np.vstack((A,B))
hstck=np.hstack((A,B))
print("Vertical Stack is\n", vstck)
print("")
print("Horizontal Stack is\n", hstck)


Vertical Stack is
 [[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]
 [11 12 13]]

Horizontal Stack is
 [[ 1  2  3  8  9 10]
 [ 4  5  6 11 12 13]]
